<?xml version="1.0" enconding="UTF-8"?>

<definitions name="Service" targetNamespace="urn:Service" xmlns:typens="urn:Service" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/">

    <message name="saludo" />
    <message name="saludoResponse">
        <part name="saludoReturn" type="xsd:string" />
    </message>

    <portType name="CursoPHPPortType">
        <operation name="saludo">
            <input message="typens:saludo" />
            <output message="typens:saludoResponse" />
        </operation>
    </portType>

    <binding name="CursoPHPBinding" type="typens:CursoPHPPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
        <operation name="saludo">
            <soap:operation soapAction="urn:saludoAction" />
            <input>
                <soap:body namespace="urn:Service" use="encoding" encondingType="http://schemas.xmlsoap.org/soap/encoding/" />
            </input>
            <output>
                <soap:body namespace="urn:Service" use="encoding" encondingType="http://schemas.xmlsoap.org/soap/encoding/" />
            </output>
        </operation>
    </binding>

    

</definitions>