<?xml version="1.0" encoding="UTF-8"?>

<definitions name="Service" targetNamespace="urn:Service" xmlns:typens="urn:Service" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/">

    <message name="saludo" />
    <message name="saludoResponse">
        <part name="saludoReturn" type="xsd:string" />
    </message>

    <message name="sumar">
        <part name="n1" type="xsd:integer" />
        <part name="n2" type="xsd:integer" />
    </message>
    <message name="sumarResponse">
        <part name="sumaResultado" type="xsd:integer" />
    </message>

    <portType name="CursoPHPPortType">
        <operation name="saludo">
            <input message="typens:saludo" />
            <output message="typens:saludoResponse" />
        </operation>
        <operation name="sumar">
            <input message="typens:sumar" />
            <output message="typens:sumarResponse" />
        </operation>
    </portType>

    <binding name="CursoPHPBinding" type="typens:CursoPHPPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
        <operation name="saludo">
            <soap:operation soapAction="urn:saludoAction" />
            <input>
                <soap:body namespace="urn:Service" use="encoding" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
            </input>
            <output>
                <soap:body namespace="urn:Service" use="encoding" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
            </output>
        </operation>
        <operation name="sumar">
            <soap:operation soapAction="urn:sumarAction" />
            <input>
                <soap:body namespace="urn:Service" use="encoding" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
            </input>
            <output>
                <soap:body namespace="urn:Service" use="encoding" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
            </output>
        </operation>
    </binding>

    <service name="Service">
        <port name="CursoPHPPortType" binding="CursoPHPBinding">
            <soap:address location="http://localhost/soap/servidor.php" />
        </port>
    </service>

</definitions>